### ISSUE TITLE
Question: number of programs

### ISSUE THREAD

**Issue by PLukas2018** [shrBadihi/EqBench#6]
I have a question about the number of programs in the benchmarks, I am not sure if I am overlooking something or if there is a different number of programs than is adduced in [the EqBench paper](https://people.ece.ubc.ca/mjulia/publications/EQBench_2021.pdf).
Specifically talking about the `REVE` and `CLEVER` benchmarks, I have counted:
- 22 Eq and 8 Neq programs for `REVE` (in the paper is 23 Eq and 9 Neq),
- 27 Eq and 20 Neq programs for `CLEVER` benchmark (in the paper is 29 Eq and 21 Neq).

Please let me know if I am missing something or if there is in fact different number of programs.

**Comment by anonymousresearcher2020** [comment]
Yes that's right for the number in the paper we referred to Clever and REVE paper themselves: they stated 23/9 and 29/21, respectively.

**Comment by shrBadihi** [comment]
Yes that's right for the number in the paper we referred to Clever and REVE paper themselves: they stated 23/9 and 29/21, respectively.

**Comment by PLukas2018** [comment]
Thanks for the response.

**Comment by anonymousresearcher2020** [comment]
I was able to find the missing test cases for CLEVER and added to EqBench but for REVE there is one method that is missing from all repositories.

**Comment by shrBadihi** [comment]
I was able to find the missing test cases for CLEVER and added to EqBench but for REVE there is one method that is missing from all repositories.

**Comment by FrNecas** [comment]
Hi, a follow-up to this issue -- the number of benchmarks in the README now does not match the actual number of benchmarks:

```bash
$ find . -path '*Eq/*.c' | sed 's%/[^/]*$%%' | uniq | wc -l
146
$ find . -path '*Neq/*.c' | sed 's%/[^/]*$%%' | uniq | wc -l
124
```

This is still 1 less in both the categories than what the paper mentions. Do you have any idea what could be the cause of this difference?

**Comment by shrBadihi** [comment]
Thanks for noting the mistake in README. It was for the initial version of EqBench and now is matched to the paper. Regarding the missing case, as I said earlier that is because of the REVE benchmark, there is one program that is mentioned in the paper but not found on their website. I'm still looking for that to see if I can find that.

**Comment by shrBadihi** [comment]
I've added the missing REVE case and now the benchmark matches to the paper.

**Comment by FrNecas** [comment]
Thanks a lot for your detective work!
